### ISSUE TITLE
Fix post page

### ISSUE THREAD

**Issue by shazzatherazza** [codersforcauses/home2health#87]
On the master branch, creating a post works but once it redirects to the post page this error appears:

<img width="1405" alt="Screen Shot 2020-02-16 at 4 16 30 pm" src="https://user-images.githubusercontent.com/52185121/74601330-efd31400-50d7-11ea-947e-b9da340d26eb.png">

**Comment by frinzekt** [comment]
Hi Shazza @shazzatherazza , I want to replicate the problem, but I seem to not know how to register and login because I get "The email already exists in our database." when registering. 

and I can't test it with postman as I get status `401` when trying to create a post.

Based on the error that you're getting, it seems that `this.props.categories` is undefined which maybe a result of the `Axios.get` where `response.data` is undefined.  Maybe try inspecting what the client gets as a response? 

The page you're dealing is: `./post/[id].js` calling the component `PostModalSetting.js` with categories as the `props` being passed as `[id].js` gets the categories of the current post

**Comment by shazzatherazza** [comment]
Cheers @frinzekt, I looked at the Axios.get and found that the baseUrl wasn't working, so I changed that  line to this: `const baseURL = process.env.API_BACKEND_URL || 'http://localhost:5000'` and it works now. Only problem is that for some reason using the .env variable doesn't work.

As for the login/register issue, I can't seem to replicate it myself. You could check that the backend .env file has the required SECRET_KEY variable, if not could you try logging out some of the errors and showing them to me? You'll find the register route in /backend/routes/user.js.

**Comment by frinzekt** [comment]
I do have the env var `SECRET_KEY=somevalue` 

Network Log
![image](https://user-images.githubusercontent.com/44391389/74618563-63733080-516d-11ea-8286-44a34a67e87b.png)

Express Log
```
OPTIONS /users/register 204 5.654 ms - 0
POST /users/register 500 208.756 ms - 2
```

**Comment by shazzatherazza** [comment]
Nice work @frinzekt. As for the post page, the issue seems to be in retrieving the backend url from the .env file. Any chance you know how to fix it?

**Comment by frinzekt** [comment]
@shazzatherazza is there a problem to retrieving the backend url from the `.env` file?
**To emphasis: I am referring to the frontend `.env` file**

The content of my frontend `env` file is :
```API_BACKEND_URL=http://localhost:4000``` which corresponds to the backend `env` file ```
PORT=4000
FRONTEND_URL=http://localhost:3000```

I don't know what seems to be the problem because mine successfully retrieves `.env` file.

**Comment by shazzatherazza** [comment]
Huh… Mine seems to be working now. Never mind, cheers @frinzekt.
